/*

undefined
MaaS customer schema

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as t from 'io-ts';
import * as Fare_ from 'maas-schemas-ts/core/components/fare';
import * as Units_ from 'maas-schemas-ts/core/components/units';
import * as Common_ from 'maas-schemas-ts/core/components/common';
import * as Address_ from 'maas-schemas-ts/core/components/address';
import * as I18n_ from 'maas-schemas-ts/core/components/i18n';
import { NonEmptyArray } from 'fp-ts/lib/NonEmptyArray';
import { nonEmptyArray } from 'io-ts-types/lib/nonEmptyArray';

type Defined =
  | Record<string, unknown>
  | Array<unknown>
  | string
  | boolean
  | number
  | null;
const Defined = t.union([
  t.UnknownRecord,
  t.UnknownArray,
  t.string,
  t.boolean,
  t.number,
  t.null,
]);

export const schemaId = 'http://maasglobal.com/core/customer.json';

// WmpAmount
// An amount of in-app credits
export type WmpAmount = t.Branded<number, WmpAmountBrand>;
export const WmpAmount = t.brand(
  t.number,
  (x): x is t.Branded<number, WmpAmountBrand> => Number.isInteger(x),
  'WmpAmount',
);
export interface WmpAmountBrand {
  readonly WmpAmount: unique symbol;
}
/** examplesWmpAmount // => { _tag: 'Right', right: examplesWmpAmountJson } */
export const examplesWmpAmountJson: NonEmptyArray<unknown> = [1234];
export const examplesWmpAmount = nonEmptyArray(WmpAmount).decode(examplesWmpAmountJson);

// WmpBalance
// An amount of in-app credits, with currency type info
export type WmpBalance = t.Branded<
  {
    currency?: 'WMP';
    amount?: WmpAmount;
  } & {
    currency: Defined;
    amount: Defined;
  },
  WmpBalanceBrand
>;
export const WmpBalance = t.brand(
  t.intersection([
    t.partial({
      currency: t.literal('WMP'),
      amount: WmpAmount,
    }),
    t.type({
      currency: Defined,
      amount: Defined,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      currency?: 'WMP';
      amount?: WmpAmount;
    } & {
      currency: Defined;
      amount: Defined;
    },
    WmpBalanceBrand
  > => true,
  'WmpBalance',
);
export interface WmpBalanceBrand {
  readonly WmpBalance: unique symbol;
}
/** examplesWmpBalance // => { _tag: 'Right', right: examplesWmpBalanceJson } */
export const examplesWmpBalanceJson: NonEmptyArray<unknown> = [
  { currency: 'WMP', amount: 1234, type: 'charge' },
];
export const examplesWmpBalance = nonEmptyArray(WmpBalance).decode(
  examplesWmpBalanceJson,
);

// TokenAmount
// An amount of in-app tokens
export type TokenAmount = t.Branded<number, TokenAmountBrand>;
export const TokenAmount = t.brand(
  t.number,
  (x): x is t.Branded<number, TokenAmountBrand> => Number.isInteger(x),
  'TokenAmount',
);
export interface TokenAmountBrand {
  readonly TokenAmount: unique symbol;
}
/** examplesTokenAmount // => { _tag: 'Right', right: examplesTokenAmountJson } */
export const examplesTokenAmountJson: NonEmptyArray<unknown> = [1];
export const examplesTokenAmount = nonEmptyArray(TokenAmount).decode(
  examplesTokenAmountJson,
);

// TokenBalance
// key would typically match tokenId
export type TokenBalance = t.Branded<
  {
    currency?: 'TOKEN';
    tokenId?: Fare_.TokenId;
    amount?: TokenAmount | null;
  } & {
    currency: Defined;
    tokenId: Defined;
    amount: Defined;
  },
  TokenBalanceBrand
>;
export const TokenBalance = t.brand(
  t.intersection([
    t.partial({
      currency: t.literal('TOKEN'),
      tokenId: Fare_.TokenId,
      amount: t.union([TokenAmount, t.null]),
    }),
    t.type({
      currency: Defined,
      tokenId: Defined,
      amount: Defined,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      currency?: 'TOKEN';
      tokenId?: Fare_.TokenId;
      amount?: TokenAmount | null;
    } & {
      currency: Defined;
      tokenId: Defined;
      amount: Defined;
    },
    TokenBalanceBrand
  > => true,
  'TokenBalance',
);
export interface TokenBalanceBrand {
  readonly TokenBalance: unique symbol;
}
/** examplesTokenBalance // => { _tag: 'Right', right: examplesTokenBalanceJson } */
export const examplesTokenBalanceJson: NonEmptyArray<unknown> = [
  { currency: 'TOKEN', tokenId: 'cx-test-token_v2', amount: 1, type: 'charge' },
];
export const examplesTokenBalance = nonEmptyArray(TokenBalance).decode(
  examplesTokenBalanceJson,
);

// Balances
// A summary of in-app credit and tokens
export type Balances = t.Branded<
  ({
    WMP?: WmpBalance;
  } & Record<string, WmpBalance | TokenBalance>) & {
    WMP: Defined;
  },
  BalancesBrand
>;
export const Balances = t.brand(
  t.intersection([
    t.intersection([
      t.partial({
        WMP: WmpBalance,
      }),
      t.record(t.string, t.union([WmpBalance, TokenBalance])),
    ]),
    t.type({
      WMP: Defined,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    ({
      WMP?: WmpBalance;
    } & Record<string, WmpBalance | TokenBalance>) & {
      WMP: Defined;
    },
    BalancesBrand
  > => true,
  'Balances',
);
export interface BalancesBrand {
  readonly Balances: unique symbol;
}
/** examplesBalances // => { _tag: 'Right', right: examplesBalancesJson } */
export const examplesBalancesJson: NonEmptyArray<unknown> = [
  {
    WMP: { currency: 'WMP', amount: 1234, type: 'charge' },
    'cx-test-token_v2': {
      currency: 'TOKEN',
      tokenId: 'cx-test-token_v2',
      amount: 1,
      type: 'charge',
    },
  },
];
export const examplesBalances = nonEmptyArray(Balances).decode(examplesBalancesJson);

// Customer
// The default export. More information at the top.
export type Customer = t.Branded<
  {
    identityId?: Units_.IdentityId;
    firstName?: Common_.PersonalName;
    lastName?: Common_.PersonalName;
    phone?: Common_.Phone;
    email?: Common_.Email;
    address?: Address_.Address;
    city?: Address_.City;
    country?: Address_.Country;
    zipCode?: Address_.ZipCode;
    locale?: I18n_.Locale;
    appInstanceId?: Common_.AppInstanceId;
    opaqueId?: Common_.OpaqueId;
    clientId?: Common_.ClientId;
    dob?: boolean | Units_.IsoDate;
    ssid?: boolean | Common_.Ssid;
    balances?: Balances;
    subscriberType?: string;
    authToken?: Common_.EncodedQueryParam;
  },
  CustomerBrand
>;
export const Customer = t.brand(
  t.partial({
    identityId: Units_.IdentityId,
    firstName: Common_.PersonalName,
    lastName: Common_.PersonalName,
    phone: Common_.Phone,
    email: Common_.Email,
    address: Address_.Address,
    city: Address_.City,
    country: Address_.Country,
    zipCode: Address_.ZipCode,
    locale: I18n_.Locale,
    appInstanceId: Common_.AppInstanceId,
    opaqueId: Common_.OpaqueId,
    clientId: Common_.ClientId,
    dob: t.union([t.boolean, Units_.IsoDate]),
    ssid: t.union([t.boolean, Common_.Ssid]),
    balances: Balances,
    subscriberType: t.string,
    authToken: Common_.EncodedQueryParam,
  }),
  (
    x,
  ): x is t.Branded<
    {
      identityId?: Units_.IdentityId;
      firstName?: Common_.PersonalName;
      lastName?: Common_.PersonalName;
      phone?: Common_.Phone;
      email?: Common_.Email;
      address?: Address_.Address;
      city?: Address_.City;
      country?: Address_.Country;
      zipCode?: Address_.ZipCode;
      locale?: I18n_.Locale;
      appInstanceId?: Common_.AppInstanceId;
      opaqueId?: Common_.OpaqueId;
      clientId?: Common_.ClientId;
      dob?: boolean | Units_.IsoDate;
      ssid?: boolean | Common_.Ssid;
      balances?: Balances;
      subscriberType?: string;
      authToken?: Common_.EncodedQueryParam;
    },
    CustomerBrand
  > => true,
  'Customer',
);
export interface CustomerBrand {
  readonly Customer: unique symbol;
}
/** examplesCustomer // => { _tag: 'Right', right: examplesCustomerJson } */
export const examplesCustomerJson: NonEmptyArray<unknown> = [
  {
    identityId: 'eu-west-1:4828507e-683f-41bf-9d87-689808fbf958',
    id: 1234,
    favoriteLocations: [],
    phone: '+358407654321',
    email: 'bob.customer@example.com',
    firstName: 'Bob',
    lastName: 'Customer',
    created: 1553687004207,
    modified: 1553688004207,
    paymentMethod: { type: 'unknown', valid: false },
    subscriptionInstance: {
      id: 10,
      name: 'Whim to Go',
      plan: { id: 'fi-whim-payg_v2' },
      addons: { '0': 'eur-whim-rollover-100_v1', '1': 'fi-whim-car' },
      region: {
        id: 'fi-helsinki',
        name: 'Helsinki Region',
        active: true,
        hidden: false,
        created: '2019-03-27T14:00:00.12345+00:00',
        zipCode: '00100',
        currency: 'EUR',
        location: { lat: 60.1699, lon: 24.9384 },
        geometryId: 2,
        countryCode: 'FI',
        countryDefault: true,
      },
      coupons: [],
      topUpId: 'fi-whim-top-up',
      wmpGrant: 0,
      pointCost: 0.01,
      description: 'Pay for each trip as you go',
    },
    balances: {
      WMP: { currency: 'WMP', amount: 1234, type: 'charge' },
      'cx-test-token_v2': {
        currency: 'TOKEN',
        tokenId: 'cx-test-token_v2',
        amount: 1,
        type: 'charge',
      },
    },
    regionId: 'fi-helsinki',
    region: {
      id: 'fi-helsinki',
      name: 'Helsinki Region',
      countryCode: 'FI',
      countryDefault: true,
      zipCode: '00100',
      location: { lat: 60.1699, lon: 24.9384 },
      active: true,
      hidden: false,
      geometryId: 2,
      created: 1553687004207,
      modified: 0,
      currency: 'EUR',
    },
    balance: 1234,
  },
];
export const examplesCustomer = nonEmptyArray(Customer).decode(examplesCustomerJson);

export default Customer;

// Success
