/*

undefined
The base leg object with all fields, to be inherited

!!! AUTO GENERATED BY CONVERT.TS REFRAIN FROM MANUAL EDITING !!!

*/

import * as State_ from 'maas-schemas-ts/core/components/state';
import * as Place_ from 'maas-schemas-ts/core/components/place';
import * as Units_ from 'maas-schemas-ts/core/components/units';
import * as t from 'io-ts';
import * as TravelMode_ from 'maas-schemas-ts/core/components/travel-mode';
import * as Stop_ from 'maas-schemas-ts/core/stop';
import * as UnitsGeo_ from 'maas-schemas-ts/core/components/units-geo';
import * as Common_ from 'maas-schemas-ts/core/components/common';
import * as BookingOption_ from 'maas-schemas-ts/core/booking-option';

type Defined =
  | Record<string, unknown>
  | Array<unknown>
  | string
  | boolean
  | number
  | null;
const Defined = t.union([
  t.UnknownRecord,
  t.UnknownArray,
  t.string,
  t.boolean,
  t.number,
  t.null,
]);

export const schemaId = 'http://maasglobal.com/core/leg.json';
// State
// The purpose of this remains a mystery
export type State = State_.LegState;
export const State = State_.LegState;
export const jsonStateExamples: Array<unknown> = [];
export const safeStateExamples = t.array(State).decode(jsonStateExamples);

// From
// The purpose of this remains a mystery
export type From = Place_.Default;
export const From = Place_.Default;
export const jsonFromExamples: Array<unknown> = [];
export const safeFromExamples = t.array(From).decode(jsonFromExamples);

// To
// The purpose of this remains a mystery
export type To = Place_.Default;
export const To = Place_.Default;
export const jsonToExamples: Array<unknown> = [];
export const safeToExamples = t.array(To).decode(jsonToExamples);

// StartTime
// The purpose of this remains a mystery
export type StartTime = Units_.Time;
export const StartTime = Units_.Time;
export const jsonStartTimeExamples: Array<unknown> = [];
export const safeStartTimeExamples = t.array(StartTime).decode(jsonStartTimeExamples);

// EndTime
// The purpose of this remains a mystery
export type EndTime = Units_.Time;
export const EndTime = Units_.Time;
export const jsonEndTimeExamples: Array<unknown> = [];
export const safeEndTimeExamples = t.array(EndTime).decode(jsonEndTimeExamples);

// Mode
// The purpose of this remains a mystery
export type Mode = t.Branded<
  | TravelMode_.PersonalMode
  | TravelMode_.PublicTransitMode
  | TravelMode_.PrivateTransitMode,
  ModeBrand
>;
export const Mode = t.brand(
  t.union([
    TravelMode_.PersonalMode,
    TravelMode_.PublicTransitMode,
    TravelMode_.PrivateTransitMode,
  ]),
  (
    x,
  ): x is t.Branded<
    | TravelMode_.PersonalMode
    | TravelMode_.PublicTransitMode
    | TravelMode_.PrivateTransitMode,
    ModeBrand
  > => true,
  'Mode',
);
export interface ModeBrand {
  readonly Mode: unique symbol;
}
export const jsonModeExamples: Array<unknown> = [null];
export const safeModeExamples = t.array(Mode).decode(jsonModeExamples);

// Stops
// The purpose of this remains a mystery
export type Stops = t.Branded<Array<Stop_.Default>, StopsBrand>;
export const Stops = t.brand(
  t.array(Stop_.Default),
  (x): x is t.Branded<Array<Stop_.Default>, StopsBrand> => true,
  'Stops',
);
export interface StopsBrand {
  readonly Stops: unique symbol;
}
export const jsonStopsExamples: Array<unknown> = [null];
export const safeStopsExamples = t.array(Stops).decode(jsonStopsExamples);

// DepartureDelay
// The purpose of this remains a mystery
export type DepartureDelay = Units_.Duration;
export const DepartureDelay = Units_.Duration;
export const jsonDepartureDelayExamples: Array<unknown> = [];
export const safeDepartureDelayExamples = t
  .array(DepartureDelay)
  .decode(jsonDepartureDelayExamples);

// ArrivalDelay
// The purpose of this remains a mystery
export type ArrivalDelay = Units_.Duration;
export const ArrivalDelay = Units_.Duration;
export const jsonArrivalDelayExamples: Array<unknown> = [];
export const safeArrivalDelayExamples = t
  .array(ArrivalDelay)
  .decode(jsonArrivalDelayExamples);

// Distance
// The purpose of this remains a mystery
export type Distance = UnitsGeo_.Distance;
export const Distance = UnitsGeo_.Distance;
export const jsonDistanceExamples: Array<unknown> = [];
export const safeDistanceExamples = t.array(Distance).decode(jsonDistanceExamples);

// Route
// The purpose of this remains a mystery
export type Route = t.Branded<string, RouteBrand>;
export const Route = t.brand(
  t.string,
  (x): x is t.Branded<string, RouteBrand> =>
    (typeof x !== 'string' || x.length >= 1) &&
    (typeof x !== 'string' || x.length <= 255),
  'Route',
);
export interface RouteBrand {
  readonly Route: unique symbol;
}
export const jsonRouteExamples: Array<unknown> = [null];
export const safeRouteExamples = t.array(Route).decode(jsonRouteExamples);

// RouteShortName
// The purpose of this remains a mystery
export type RouteShortName = t.Branded<string, RouteShortNameBrand>;
export const RouteShortName = t.brand(
  t.string,
  (x): x is t.Branded<string, RouteShortNameBrand> =>
    (typeof x !== 'string' || x.length >= 1) && (typeof x !== 'string' || x.length <= 64),
  'RouteShortName',
);
export interface RouteShortNameBrand {
  readonly RouteShortName: unique symbol;
}
export const jsonRouteShortNameExamples: Array<unknown> = [null];
export const safeRouteShortNameExamples = t
  .array(RouteShortName)
  .decode(jsonRouteShortNameExamples);

// RouteLongName
// The purpose of this remains a mystery
export type RouteLongName = t.Branded<string, RouteLongNameBrand>;
export const RouteLongName = t.brand(
  t.string,
  (x): x is t.Branded<string, RouteLongNameBrand> =>
    (typeof x !== 'string' || x.length >= 1) &&
    (typeof x !== 'string' || x.length <= 255),
  'RouteLongName',
);
export interface RouteLongNameBrand {
  readonly RouteLongName: unique symbol;
}
export const jsonRouteLongNameExamples: Array<unknown> = [null];
export const safeRouteLongNameExamples = t
  .array(RouteLongName)
  .decode(jsonRouteLongNameExamples);

// AgencyId
// The purpose of this remains a mystery
export type AgencyId = Common_.AgencyId;
export const AgencyId = Common_.AgencyId;
export const jsonAgencyIdExamples: Array<unknown> = [];
export const safeAgencyIdExamples = t.array(AgencyId).decode(jsonAgencyIdExamples);

// LegGeometry
// The purpose of this remains a mystery
export type LegGeometry = t.Branded<
  {
    points?: UnitsGeo_.Polyline;
  },
  LegGeometryBrand
>;
export const LegGeometry = t.brand(
  t.partial({
    points: UnitsGeo_.Polyline,
  }),
  (
    x,
  ): x is t.Branded<
    {
      points?: UnitsGeo_.Polyline;
    },
    LegGeometryBrand
  > => true,
  'LegGeometry',
);
export interface LegGeometryBrand {
  readonly LegGeometry: unique symbol;
}
export const jsonLegGeometryExamples: Array<unknown> = [null];
export const safeLegGeometryExamples = t
  .array(LegGeometry)
  .decode(jsonLegGeometryExamples);

// TspProduct
// The purpose of this remains a mystery
export type TspProduct = BookingOption_.TspProduct;
export const TspProduct = BookingOption_.TspProduct;
export const jsonTspProductExamples: Array<unknown> = [];
export const safeTspProductExamples = t.array(TspProduct).decode(jsonTspProductExamples);

// ProductOption
// Index of the productOption used in the itinerary's productOptions
export type ProductOption = t.Branded<number, ProductOptionBrand>;
export const ProductOption = t.brand(
  t.number,
  (x): x is t.Branded<number, ProductOptionBrand> => Number.isInteger(x),
  'ProductOption',
);
export interface ProductOptionBrand {
  readonly ProductOption: unique symbol;
}
export const jsonProductOptionExamples: Array<unknown> = [null];
export const safeProductOptionExamples = t
  .array(ProductOption)
  .decode(jsonProductOptionExamples);

// LegExtensions
// MaaS specific leg extensions
export type LegExtensions = t.Branded<
  {
    id?: Units_.Uuid;
    signature?: Common_.Signature;
  },
  LegExtensionsBrand
>;
export const LegExtensions = t.brand(
  t.partial({
    id: Units_.Uuid,
    signature: Common_.Signature,
  }),
  (
    x,
  ): x is t.Branded<
    {
      id?: Units_.Uuid;
      signature?: Common_.Signature;
    },
    LegExtensionsBrand
  > => true,
  'LegExtensions',
);
export interface LegExtensionsBrand {
  readonly LegExtensions: unique symbol;
}
export const jsonLegExtensionsExamples: Array<unknown> = [null];
export const safeLegExtensionsExamples = t
  .array(LegExtensions)
  .decode(jsonLegExtensionsExamples);

// LegCore
// The purpose of this remains a mystery
export type LegCore = t.Branded<
  {
    state?: State;
    from?: From;
    to?: To;
    startTime?: StartTime;
    endTime?: EndTime;
    mode?: Mode;
    stops?: Stops;
    departureDelay?: DepartureDelay;
    arrivalDelay?: ArrivalDelay;
    distance?: Distance;
    route?: Route;
    routeShortName?: RouteShortName;
    routeLongName?: RouteLongName;
    agencyId?: AgencyId;
    legGeometry?: LegGeometry;
    tspProduct?: TspProduct;
    productOption?: ProductOption;
  } & {
    from: Defined;
    to: Defined;
    mode: Defined;
    startTime: Defined;
    endTime: Defined;
    legGeometry: Defined;
  },
  LegCoreBrand
>;
export const LegCore = t.brand(
  t.intersection([
    t.partial({
      state: State,
      from: From,
      to: To,
      startTime: StartTime,
      endTime: EndTime,
      mode: Mode,
      stops: Stops,
      departureDelay: DepartureDelay,
      arrivalDelay: ArrivalDelay,
      distance: Distance,
      route: Route,
      routeShortName: RouteShortName,
      routeLongName: RouteLongName,
      agencyId: AgencyId,
      legGeometry: LegGeometry,
      tspProduct: TspProduct,
      productOption: ProductOption,
    }),
    t.type({
      from: Defined,
      to: Defined,
      mode: Defined,
      startTime: Defined,
      endTime: Defined,
      legGeometry: Defined,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      state?: State;
      from?: From;
      to?: To;
      startTime?: StartTime;
      endTime?: EndTime;
      mode?: Mode;
      stops?: Stops;
      departureDelay?: DepartureDelay;
      arrivalDelay?: ArrivalDelay;
      distance?: Distance;
      route?: Route;
      routeShortName?: RouteShortName;
      routeLongName?: RouteLongName;
      agencyId?: AgencyId;
      legGeometry?: LegGeometry;
      tspProduct?: TspProduct;
      productOption?: ProductOption;
    } & {
      from: Defined;
      to: Defined;
      mode: Defined;
      startTime: Defined;
      endTime: Defined;
      legGeometry: Defined;
    },
    LegCoreBrand
  > => true,
  'LegCore',
);
export interface LegCoreBrand {
  readonly LegCore: unique symbol;
}
export const jsonLegCoreExamples: Array<unknown> = [null];
export const safeLegCoreExamples = t.array(LegCore).decode(jsonLegCoreExamples);

// WaitingLeg
// The purpose of this remains a mystery
export type WaitingLeg = t.Branded<
  {
    startTime?: Units_.Time;
    endTime?: Units_.Time;
    mode?: TravelMode_.WaitingMode;
  } & {
    mode: Defined;
    startTime: Defined;
    endTime: Defined;
  },
  WaitingLegBrand
>;
export const WaitingLeg = t.brand(
  t.intersection([
    t.partial({
      startTime: Units_.Time,
      endTime: Units_.Time,
      mode: TravelMode_.WaitingMode,
    }),
    t.type({
      mode: Defined,
      startTime: Defined,
      endTime: Defined,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      startTime?: Units_.Time;
      endTime?: Units_.Time;
      mode?: TravelMode_.WaitingMode;
    } & {
      mode: Defined;
      startTime: Defined;
      endTime: Defined;
    },
    WaitingLegBrand
  > => true,
  'WaitingLeg',
);
export interface WaitingLegBrand {
  readonly WaitingLeg: unique symbol;
}
export const jsonWaitingLegExamples: Array<unknown> = [null];
export const safeWaitingLegExamples = t.array(WaitingLeg).decode(jsonWaitingLegExamples);

// TransferLeg
// The purpose of this remains a mystery
export type TransferLeg = t.Branded<
  {
    startTime?: Units_.Time;
    endTime?: Units_.Time;
    mode?: TravelMode_.TransferMode;
  } & {
    mode: Defined;
    startTime: Defined;
    endTime: Defined;
  },
  TransferLegBrand
>;
export const TransferLeg = t.brand(
  t.intersection([
    t.partial({
      startTime: Units_.Time,
      endTime: Units_.Time,
      mode: TravelMode_.TransferMode,
    }),
    t.type({
      mode: Defined,
      startTime: Defined,
      endTime: Defined,
    }),
  ]),
  (
    x,
  ): x is t.Branded<
    {
      startTime?: Units_.Time;
      endTime?: Units_.Time;
      mode?: TravelMode_.TransferMode;
    } & {
      mode: Defined;
      startTime: Defined;
      endTime: Defined;
    },
    TransferLegBrand
  > => true,
  'TransferLeg',
);
export interface TransferLegBrand {
  readonly TransferLeg: unique symbol;
}
export const jsonTransferLegExamples: Array<unknown> = [null];
export const safeTransferLegExamples = t
  .array(TransferLeg)
  .decode(jsonTransferLegExamples);

// Default
// The default export. More information at the top.
export type Default = t.Branded<
  {} & (LegExtensions & (LegCore | WaitingLeg | TransferLeg)),
  DefaultBrand
>;
export const Default = t.brand(
  t.intersection([
    t.type({}),
    t.intersection([LegExtensions, t.union([LegCore, WaitingLeg, TransferLeg])]),
  ]),
  (
    x,
  ): x is t.Branded<
    {} & (LegExtensions & (LegCore | WaitingLeg | TransferLeg)),
    DefaultBrand
  > => true,
  'Default',
);
export interface DefaultBrand {
  readonly Default: unique symbol;
}
export const jsonDefaultExamples: Array<unknown> = [null];
export const safeDefaultExamples = t.array(Default).decode(jsonDefaultExamples);

export default Default;

// Success
